title: Yichao Huang
description: young researcher working on Gaussian Multiplicative Chaos and Liouville Quantum Gravity.
show_downloads: false
google_analytics: UA-106929604-1
theme: jekyll-theme-minimal