title: Yichao Huang
description: oung researcher in mathematics, specializing in probability theory and mathematical physics.
show_downloads: false
google_analytics: UA-106929604-1
theme: jekyll-theme-minimal