title: Yichao Huang
description: just another Mathematical playground
shortbio: I'm a young researcher in Probability, working on Multiplicative Gaussian Chaos and Liouville Quantum Gravity.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal