# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Yichao Huang
tagline:          
description:      
url:              http://yichao.github.io

author:
  name:           Yichao Huang
  url:            http://yichao.github.io

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           
